apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore-service
  labels:
    app: bookstore-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookstore-service
      example: bookstore-service
  template:
    metadata:
      labels:
        app: bookstore-service
        example: bookstore-service
    spec:
      containers:
        - name: bookstore-service
          image: kwiatekus/bookstore
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 100m
              memory: 256Mi
            requests:
              cpu: 20m
              memory: 32Mi

